import type { Metadata } from 'next'
import Link from 'next/link'
import {
  Upload,
  Ruler,
  BookOpen,
  Table2,
  FileOutput,
  SearchCheck,
  ArrowRight,
  CheckCircle2,
  XCircle,
  ChevronRight,
  Link2,
  Zap,
} from 'lucide-react'
import { CtaStripSection } from '@/components/sections/CtaStripSection'

export const metadata: Metadata = {
  title: 'AI Estimation & Tender — ConstructIQ',
  description:
    'Upload drawings, get instant BOQ. CPWD/PWD-rate BOQs and NIT documents generated by AI.',
}

const features = [
  {
    icon: Upload,
    title: 'Drawing Upload & Parsing',
    description:
      'Upload architectural and structural drawings in PDF or DWG format. The AI engine reads floor plans, sections, and elevations — extracting room dimensions, wall lengths, slab areas, and structural members automatically.',
  },
  {
    icon: Ruler,
    title: 'Quantity Extraction',
    description:
      "Floor-wise quantity takeoff for earthwork, concrete, masonry, plastering, flooring, paint, waterproofing, and MEP rough-ins. Accuracy within 3–5% of a senior quantity surveyor's manual takeoff.",
  },
  {
    icon: BookOpen,
    title: 'Rate Database (CPWD/PWD/DSR)',
    description:
      'Integrated with current Central PWD, state PWD, and District Schedule of Rates databases. Rates auto-applied by district and financial year. Updated quarterly from official gazette notifications.',
  },
  {
    icon: Table2,
    title: 'BOQ Generation',
    description:
      'Full Bill of Quantities output: item description, unit, quantity, rate, and amount — broken by trade and sub-trade. Export to Excel, PDF, or push directly into the Construction Packages module.',
  },
  {
    icon: FileOutput,
    title: 'Tender Document Output',
    description:
      'NIT-ready Notice Inviting Tender documents generated alongside the BOQ — conditions of contract, scope of work, technical specifications, and schedule of quantities in the PWD standard format.',
  },
  {
    icon: SearchCheck,
    title: 'Contractor Quote Audit',
    description:
      "Upload a contractor's quote and the platform audits it line by line against your AI-generated BOQ. Over-billing flagged in red, under-specified items highlighted in amber. Negotiate with data.",
  },
]

const steps = [
  {
    n: '01',
    title: 'Upload PDF/DWG drawings',
    desc: 'Upload your architectural drawings — ground floor plan, upper floor plan, and structural layout. The AI parser identifies walls, openings, columns, beams, slabs, staircases, and roof elements from the drawing geometry.',
  },
  {
    n: '02',
    title: 'AI extracts quantities and applies rates',
    desc: 'The engine runs a complete quantity takeoff trade by trade — excavation, PCC, RCC, brickwork, plaster, tiles, painting, and electrification. Current CPWD/PWD rates for your district and financial year are applied automatically.',
  },
  {
    n: '03',
    title: 'Download BOQ and NIT documents',
    desc: 'Review the BOQ in the platform editor. Edit quantities or rates if needed. Download the final BOQ in Excel or PDF. Generate NIT-ready tender documents for government procurement or competitive contractor bidding in one click.',
  },
]

const stats = [
  { value: '<15 min', label: 'BOQ generation from uploaded drawings' },
  { value: '3–5%', label: 'Quantity accuracy vs. manual QS takeoff' },
  { value: '1000+', label: 'Rate line items from CPWD/PWD/DSR databases' },
]

const beforeAfter = [
  {
    before: 'Hire a Quantity Surveyor — 7–15 days, ₹20,000–₹80,000 fee per project',
    after: 'Upload drawings, get a BOQ in under 15 minutes — no QS fee',
  },
  {
    before: "Contractor quote has no basis — you can't tell if ₹45L is fair or padded",
    after: 'AI BOQ audit compares contractor line-by-line — padding is visible immediately',
  },
  {
    before: 'Government tender requires NIT format — requires specialist document preparation',
    after: 'NIT-ready tender documents generated alongside BOQ in one workflow',
  },
]

const integrations = [
  {
    module: 'Construction Packages',
    href: '/platform/construction-packages',
    desc: 'BOQ flows directly into Construction Packages for contractor matching — your drawing-derived quantities replace the default package BOQ for a fully customized build.',
  },
  {
    module: 'Construction Finance',
    href: '/platform/construction-finance',
    desc: 'Finance module uses the AI-generated BOQ for loan structuring — accurate, itemized costs give banks the documentation they need to underwrite your project.',
  },
  {
    module: 'Material Supply',
    href: '/platform/material-supply',
    desc: 'Material quantities from the BOQ feed into Material Supply for procurement — cement, steel, and aggregate quantities are auto-populated from your drawing takeoff.',
  },
]

export default function AiEstimationPage() {
  return (
    <>
      {/* ── HERO ─────────────────────────────────────────────────────────────── */}
      <section
        className="relative grain-overlay overflow-hidden py-24 lg:py-32"
        style={{ backgroundColor: '#0A1628' }}
        aria-labelledby="ai-hero-heading"
      >
        <div
          className="pointer-events-none absolute inset-0 opacity-20"
          aria-hidden="true"
          style={{
            backgroundImage:
              'linear-gradient(rgba(59,130,246,0.15) 1px, transparent 1px), linear-gradient(90deg, rgba(59,130,246,0.15) 1px, transparent 1px)',
            backgroundSize: '56px 56px',
          }}
        />
        {/* Steel-blue AI glow */}
        <div
          className="pointer-events-none absolute bottom-0 left-1/2 w-[800px] h-[400px] opacity-10"
          aria-hidden="true"
          style={{
            background: 'radial-gradient(ellipse, var(--color-ciq-steel) 0%, transparent 70%)',
            transform: 'translate(-50%, 40%)',
          }}
        />
        <div className="relative z-10 mx-auto max-w-[1280px] px-4 md:px-6 lg:px-8">
          <nav className="mb-6 flex items-center gap-2 text-xs text-[color:var(--color-ciq-concrete)]" aria-label="Breadcrumb">
            <Link href="/" className="hover:text-white transition-colors">Home</Link>
            <ChevronRight size={12} />
            <Link href="/#platform" className="hover:text-white transition-colors">Platform</Link>
            <ChevronRight size={12} />
            <span style={{ color: 'var(--color-ciq-safety)' }}>AI Estimation</span>
          </nav>

          <p className="pretitle">Phase 05 / AI Estimation</p>

          {/* AI badge */}
          <div
            className="mt-2 inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold border"
            style={{
              borderColor: 'rgba(59,130,246,0.3)',
              backgroundColor: 'rgba(59,130,246,0.08)',
              color: 'var(--color-ciq-steel)',
            }}
          >
            <Zap size={12} />
            Powered by computer vision + rate database AI
          </div>

          <h1
            id="ai-hero-heading"
            className="font-display font-bold text-white mt-4 text-[36px] md:text-[48px] lg:text-[56px] leading-[1.05] max-w-3xl"
          >
            Upload drawings.{' '}
            <span style={{ color: 'var(--color-ciq-safety)' }}>Get a BOQ</span>{' '}
            in minutes.
          </h1>
          <p className="mt-6 max-w-xl text-base lg:text-lg text-[color:var(--color-ciq-concrete)]">
            AI reads your architectural and structural drawings, extracts quantities, applies current CPWD/PWD/DSR rates, and generates NIT-ready tender documents — no quantity surveyor required.
          </p>

          <div className="mt-8 flex flex-wrap gap-4">
            <Link
              href="/signup"
              className="inline-flex items-center gap-2 px-7 py-3.5 rounded-md font-semibold text-sm transition-transform hover:scale-[1.02]"
              style={{ backgroundColor: 'var(--color-ciq-safety)', color: '#0A1628' }}
            >
              Get Started <ArrowRight size={16} />
            </Link>
            <Link
              href="#features"
              className="inline-flex items-center gap-2 px-7 py-3.5 rounded-md font-semibold text-sm border border-white/[0.18] text-white hover:bg-white/[0.04] transition-colors"
            >
              Learn More
            </Link>
          </div>

          <div className="mt-16 grid grid-cols-3 gap-6 max-w-2xl">
            {stats.map((s) => (
              <div key={s.label} className="p-6 rounded-lg border border-white/[0.06] bg-white/[0.02]">
                <p
                  className="font-display font-bold text-[32px] lg:text-[40px] leading-none"
                  style={{ color: 'var(--color-ciq-steel)' }}
                >
                  {s.value}
                </p>
                <p className="mt-2 text-xs text-[color:var(--color-ciq-concrete)] leading-snug">{s.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── OVERVIEW / FEATURES ──────────────────────────────────────────────── */}
      <section
        id="features"
        className="py-24 lg:py-32"
        style={{ backgroundColor: '#F1F5F9' }}
        aria-labelledby="ai-features-heading"
      >
        <div className="mx-auto max-w-[1280px] px-4 md:px-6 lg:px-8">
          <p className="pretitle" style={{ color: 'var(--color-ciq-blueprint)' }}>What's included</p>
          <h2
            id="ai-features-heading"
            className="font-display font-bold mt-4 text-[36px] md:text-[48px] lg:text-[56px] leading-[1.05]"
            style={{ color: '#0A1628' }}
          >
            No QS. No guesswork.{' '}
            <span style={{ color: 'var(--color-ciq-safety)' }}>Just accurate BOQs.</span>
          </h2>
          <p className="mt-4 max-w-xl text-base text-slate-600">
            Quantity surveyors take weeks and cost thousands per project. ConstructIQ's AI estimation engine delivers the same output in minutes — directly linked to government-standard rate databases.
          </p>

          <div className="mt-12 rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden">
            <div className="grid grid-cols-2">
              <div className="p-5 border-b border-slate-200 bg-slate-50">
                <p className="text-xs font-semibold uppercase tracking-widest text-slate-400">Before ConstructIQ</p>
              </div>
              <div
                className="p-5 border-b border-slate-200"
                style={{ backgroundColor: 'rgba(245,158,11,0.06)' }}
              >
                <p className="text-xs font-semibold uppercase tracking-widest" style={{ color: 'var(--color-ciq-safety)' }}>
                  With ConstructIQ
                </p>
              </div>
              {beforeAfter.map((row, i) => (
                <>
                  <div key={`before-${i}`} className="flex items-start gap-3 p-5 border-b border-slate-100 last:border-0">
                    <XCircle size={16} className="mt-0.5 shrink-0 text-red-400" />
                    <p className="text-sm text-slate-600">{row.before}</p>
                  </div>
                  <div
                    key={`after-${i}`}
                    className="flex items-start gap-3 p-5 border-b border-slate-100 last:border-0"
                    style={{ backgroundColor: 'rgba(245,158,11,0.03)' }}
                  >
                    <CheckCircle2 size={16} className="mt-0.5 shrink-0" style={{ color: 'var(--color-ciq-safety)' }} />
                    <p className="text-sm text-slate-700">{row.after}</p>
                  </div>
                </>
              ))}
            </div>
          </div>

          <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((f) => (
              <div key={f.title} className="p-6 rounded-lg border border-slate-200 bg-white shadow-sm">
                <div
                  className="inline-flex items-center justify-center w-10 h-10 rounded-md mb-4"
                  style={{ backgroundColor: 'rgba(59,130,246,0.1)' }}
                >
                  <f.icon size={20} style={{ color: 'var(--color-ciq-steel)' }} />
                </div>
                <h3 className="font-semibold text-base" style={{ color: '#0A1628' }}>{f.title}</h3>
                <p className="mt-2 text-sm text-slate-600 leading-relaxed">{f.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS ─────────────────────────────────────────────────────── */}
      <section
        className="py-24 lg:py-32"
        style={{ backgroundColor: '#0A1628' }}
        aria-labelledby="ai-steps-heading"
      >
        <div className="mx-auto max-w-[1280px] px-4 md:px-6 lg:px-8">
          <p className="pretitle">How it works</p>
          <h2
            id="ai-steps-heading"
            className="font-display font-bold text-white mt-4 text-[36px] md:text-[48px] lg:text-[56px] leading-[1.05] max-w-2xl"
          >
            Drawings in.{' '}
            <span style={{ color: 'var(--color-ciq-safety)' }}>Tender-ready BOQ</span>{' '}
            out.
          </h2>

          <div className="mt-16 grid gap-8 lg:grid-cols-3">
            {steps.map((step, i) => (
              <div key={step.n} className="relative p-6 rounded-lg border border-white/[0.06] bg-white/[0.02]">
                {i < steps.length - 1 && (
                  <div
                    className="hidden lg:block absolute top-1/2 -right-4 w-8 h-[1px] opacity-30"
                    aria-hidden="true"
                    style={{ backgroundColor: 'var(--color-ciq-steel)' }}
                  />
                )}
                <p
                  className="font-display font-bold text-[48px] leading-none opacity-20"
                  style={{ color: 'var(--color-ciq-steel)' }}
                >
                  {step.n}
                </p>
                <h3 className="mt-3 font-semibold text-lg text-white">{step.title}</h3>
                <p className="mt-3 text-sm text-[color:var(--color-ciq-concrete)] leading-relaxed">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── INTEGRATIONS ─────────────────────────────────────────────────────── */}
      <section
        className="py-24 lg:py-32"
        style={{ backgroundColor: '#0A1628' }}
        aria-labelledby="ai-integrations-heading"
      >
        <div className="mx-auto max-w-[1280px] px-4 md:px-6 lg:px-8">
          <div className="border-t border-white/[0.06] pt-16">
            <p className="pretitle">Platform Connections</p>
            <h2
              id="ai-integrations-heading"
              className="font-display font-bold text-white mt-4 text-[36px] md:text-[48px] lg:text-[56px] leading-[1.05] max-w-2xl"
            >
              The BOQ that powers{' '}
              <span style={{ color: 'var(--color-ciq-safety)' }}>the entire platform.</span>
            </h2>
            <p className="mt-4 max-w-xl text-[color:var(--color-ciq-concrete)]">
              AI Estimation is the foundation layer. The BOQ it generates flows into packages, finance, and procurement — one source of truth for the whole project lifecycle.
            </p>

            <div className="mt-12 grid gap-6 md:grid-cols-3">
              {integrations.map((int) => (
                <Link
                  key={int.module}
                  href={int.href}
                  className="group p-6 rounded-lg border border-white/[0.06] bg-white/[0.02] hover:border-white/[0.12] hover:bg-white/[0.04] transition-colors"
                >
                  <div className="flex items-center justify-between">
                    <div
                      className="inline-flex items-center justify-center w-9 h-9 rounded-md"
                      style={{ backgroundColor: 'rgba(59,130,246,0.1)' }}
                    >
                      <Link2 size={16} style={{ color: 'var(--color-ciq-steel)' }} />
                    </div>
                    <ArrowRight
                      size={14}
                      className="text-[color:var(--color-ciq-concrete)] group-hover:translate-x-0.5 transition-transform"
                    />
                  </div>
                  <p className="mt-4 font-semibold text-white text-sm">{int.module}</p>
                  <p className="mt-2 text-xs text-[color:var(--color-ciq-concrete)] leading-relaxed">{int.desc}</p>
                </Link>
              ))}
            </div>
          </div>
        </div>
      </section>

      <CtaStripSection />
    </>
  )
}
